export const genreList = [
  { label: "Ficção", value: "FICTION" },
  { label: "Fantasia", value: "FANTASY" },
  { label: "Mistério", value: "MYSTERY" },
  { label: "Romance", value: "ROMANCE" },
  { label: "Biografia", value: "BIOGRAPHY" },
  { label: "Ciência", value: "SCIENCE" },
  { label: "História", value: "HISTORY" },
  { label: "Suspense", value: "THRILLER" },
  { label: "Terror", value: "HORROR" },
  { label: "Autoajuda", value: "SELF_HELP" },
  { label: "Filosofia", value: "PHILOSOPHY" },
  { label: "Poesia", value: "POETRY" },
  { label: "Aventura", value: "ADVENTURE" },
  { label: "Ficção Científica", value: "SCIENCE_FICTION" },
  { label: "Tecnologia", value: "TECHNOLOGY" },
  { label: "Negócios", value: "BUSINESS" },
  { label: "Educação", value: "EDUCATION" },
  { label: "Saúde", value: "HEALTH" },
  { label: "Quadrinhos", value: "COMICS" },
  { label: "Religião", value: "RELIGION" },
  { label: "Arte", value: "ART" },
  { label: "Viagem", value: "TRAVEL" },
  { label: "Culinária", value: "COOKING" },
  { label: "Infantil", value: "CHILDREN" },
];
